#!/bin/sh

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
kernel=$(uname -s | tr '[:upper:]' '[:lower:]')
systemd_dir=/usr/lib/systemd
x11_conf_dir=/etc/X11/xorg.conf.d
bin_dir=/usr/local/bin

if [ $(id -u) -ne 0 ]; then
  echo "Must be root"
  exit 1
fi

for script in $(ls $dir/scripts); do
  echo "Copying $dir/scripts/$script to /usr/local/bin/$script"
  cp $dir/scripts/$script /usr/local/bin/$script
  echo "Ensuring it is executable"
  chmod +x /usr/local/bin/$script
done

if [ "$kernel" = "linux" ]; then
  if [ -d /etc/systemd/system ]; then
    echo "Installing systemd units"
    for unit in $(ls $dir/systemd/install); do
      echo "Installing $unit"
      cp $dir/systemd/install/$unit /etc/systemd/system/$unit
    done
    for unit in $(ls $dir/systemd/enable); do
      echo "Installing, enabling and starting $unit"
      cp $dir/systemd/enable/$unit /etc/systemd/system/$unit
      systemctl enable $unit
      systemctl start $unit
    done
    for hook in $(find $dir/systemd/hooks -type f); do
      hook_dir=$systemd_dir/$(basename $(dirname $hook))
      if [ -d $hook_dir ]; then
          echo "Installing hook $hook in $hook_dir"
          cp $hook $hook_dir/
      else
          echo "No such hook dir $hook_dir"
      fi
    done
    echo "Please note that user services (eg. the ones with @ in"
    echo "their names) may need to be enabled after install!"
    systemctl daemon-reload
  fi
  if [ -d $x11_conf_dir ]; then
      echo "Installing X11 configuration"
      for conf in $(ls $dir/X11/xorg.conf.d); do
          echo "Installing X11 config $conf in $x11_conf_dir"
          cp $dir/X11/xorg.conf.d/$conf $x11_conf_dir/
      done
  fi
fi