#!/bin/sh

CMD="$1"
BUILT_IN=$(xrandr | grep " connected" | awk '{print $1}' | head -n +1)
DISPLAY_NAME=$(xrandr | grep " connected" | awk '{print $1}' | tail -n +2 | head -n +1)
EXT_MODE=$(xrandr | grep $DISPLAY_NAME -A 1 | tail -1 | awk '{print $1}')

if [ "" = "$DISPLAY_NAME" ]; then
  exit 1
fi

on() {
  xrandr -q | grep -C 20 ^$DISPLAY_NAME | grep -P '\d+mm x \d+mm' 2>&1 >/dev/null
}

off() {
  if on; then
    false
  else
    true
  fi
}

left_of() {
  OFFSET=$(xrandr | grep ^$DISPLAY_NAME | awk -F'+' '{print $2}')
  [ "$OFFSET" = "0" ]
}

if [ "$BLOCK_BUTTON" = "1" ]; then
  CMD="toggle"
fi

if [ "$CMD" = "toggle" ]; then
  if off; then
    CMD="right"
  else
    CMD="off"
  fi
fi

if [ "$CMD" = "right" ]; then
  xrandr --output $DISPLAY_NAME --mode "$EXT_MODE" --right-of $BUILT_IN 2>/dev/null
elif [ "$CMD" = "left" ]; then
  xrandr --output $DISPLAY_NAME --mode "$EXT_MODE" --left-of $BUILT_IN 2>/dev/null
elif [ "$CMD" = "off" ]; then
  xrandr --output $DISPLAY_NAME --off 2>/dev/null
fi

if on; then
  if left_of; then
    echo ""
  else
    echo ""
  fi
else
  echo "OFF"
fi
