#!/bin/sh

HN=$(hostname -s)

if [ -e $HOME/.i3/config.$HN ]; then
  cat $HOME/.i3/config.$HN $HOME/.i3/config.base > $HOME/.i3/config
else
  cat $HOME/.i3/config.default $HOME/.i3/config.base > $HOME/.i3/config
fi
