PATH="$HOME/.gem/ruby/2.4.0/bin:$PATH"
PATH="$HOME/Local/node_modules/.bin:$PATH"
PATH="$HOME/.luarocks/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/Local/bin:$PATH"
